### ISSUE TITLE
Content profile dropdown has no value

### ISSUE THREAD

**Issue by cavis** [publicmediaplatform/pmp-wordpress#18] opened 2015-03-06 18:14 UTC
Although it does seem to be hardcoded to "profile=story", would be nice if the disabled dropdown displayed "Story" instead of blank.

And actually, the markup looks a bit wonky for that dropdown - http://cl.ly/image/1s3L2j2x0D2R

**Comment by rnagle** [comment] 2015-03-16 18:33
I was unable to reproduce this bug.

Here's what I see: https://www.dropbox.com/s/in3pm607nxf64ak/Screen%20Shot%202015-03-16%20at%201.31.06%20PM.png?dl=0

Is this still an issue for you?

**Comment by cavis** [comment] 2015-03-17 15:33
Yep - I suspect my PHP doesn't like your short open tags - https://github.com/publicmediaplatform/pmp-wordpress/blob/7a0c870d0a721ca28018350a27d14b9558ec5f54/templates/search.php#L23

**Comment by rnagle** [comment] 2015-03-18 17:45
Ugh, I can't believe I did that. I'll fix this in my next commit. Thank you!

**Comment by rnagle** [comment] 2015-03-25 16:53
Fixed in 9d833c408017732a2e7e9eab78503c46889f125a.

**Closed by rnagle** 2015-03-25 16:53 UTC
Labels: bug
